version: '3.8'

services:
  qbin:
    image: naiher/qbin:latest
    container_name: qbin-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # 必选环境变量
      - ADMIN_PASSWORD=your_secure_admin_password  # 请修改为安全的密码
      - ADMIN_EMAIL=admin@example.com  # 请修改为您的邮箱
      - DATABASE_URL=postgres://qbin:qbinpassword@postgres:5432/qbin
      - JWT_SECRET=change_this_to_a_secure_random_string  # 请修改为随机安全字符串

      # 可选环境变量
      - PORT=8000
      - TOKEN_EXPIRE=31536000
      - MAX_UPLOAD_FILE_SIZE=52428800

      # GitHub OAuth配置（可选，如需使用请取消注释并填写）
      # - GITHUB_CLIENT_ID=your_github_client_id
      # - GITHUB_CLIENT_SECRET=your_github_client_secret
      # - GITHUB_CALLBACK_URL=http://your-domain:8000/api/login/oauth2/callback/github

      # Google OAuth配置（可选，如需使用请取消注释并填写）
      # - GOOGLE_CLIENT_ID=your_google_client_id
      # - GOOGLE_CLIENT_SECRET=your_google_client_secret
      # - GOOGLE_CALLBACK_URL=http://your-domain:8000/api/login/oauth2/callback/google

      # LinuxDO OAuth配置（可选，如需使用请取消注释并填写）
      # - LINUXDO_CLIENT_ID=your_linuxdo_client_id
      # - LINUXDO_CLIENT_SECRET=your_linuxdo_client_secret
      # - LINUXDO_CALLBACK_URL=http://your-domain:8000/api/login/oauth2/callback/linuxdo
      # - LINUXDO_USER_LEVEL=0
    ports:
      - "8000:8000"
    networks:
      - qbin-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Postgres数据库服务
  postgres:
    image: postgres:14-alpine
    container_name: qbin-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=qbin
      - POSTGRES_PASSWORD=qbinpassword
      - POSTGRES_DB=qbin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - qbin-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qbin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  postgres-data:
    driver: local

networks:
  qbin-network:
    driver: bridge
    internal: false